### ISSUE TITLE
can you please make the script compatible with https://chrome.google.com/webstore/detail/google-search-geolocation/gglakldnncaidfodbmpaodhdknnlkjbb ?

### ISSUE THREAD

**Issue by yakisova41** [yakisova41/google-search-classic-navbar#14]
@yakisova41 can you please make the script compatible with https://chrome.google.com/webstore/detail/google-search-geolocation/gglakldnncaidfodbmpaodhdknnlkjbb ?
It worked fine before but it doesn't work anymore after the latest update

_Originally posted by @Void48 in https://github.com/yakisova41/google-search-classic-navbar/issues/8#issuecomment-1793544807_

**Comment by Void48** [comment]
> ```
>           @yakisova41 can you please make the script compatible with https://chrome.google.com/webstore/detail/google-search-geolocation/gglakldnncaidfodbmpaodhdknnlkjbb ?
> ```
> 
> It worked fine before but it doesn't work anymore after the latest update
> 
> _Originally posted by @Void48 in [#8 (comment)](https://github.com/yakisova41/google-search-classic-navbar/issues/8#issuecomment-1793544807)_

you can close this issue since it works now with the extension
