### ISSUE TITLE
Now it's being replaced with a huge block of nothingness...

### ISSUE THREAD

**Issue by yakisova41** [yakisova41/google-search-classic-navbar#17]
@yakisova41
Now it's being replaced with a huge block of nothingness...
![Screenshot_2024-01-01 date_default_timezone_set - Google Search](https://github.com/yakisova41/google-search-classic-navbar/assets/51834343/b2d7a937-1bd4-4b5f-96b5-67b187df84e4)

_Originally posted by @ljcool2006 in https://github.com/yakisova41/google-search-classic-navbar/issues/8#issuecomment-1873196935_

**Comment by yakisova41** [comment]
@ljcool2006
I have searched with the same keywords and it works fine.
Are there any errors displayed in the console that can be seen by pressing F12?
The region is set to United States and the language is set to English.
![スクリーンショット 2024-01-02 002511](https://github.com/yakisova41/google-search-classic-navbar/assets/75610521/4ec65a21-59a3-4add-8e2d-9937298d65e3)

**Comment by ljcool2006** [comment]
i did this in a private window so i probably wouldn't be able to reproduce it again; i don't think there were any errors related to the script

**Comment by yakisova41** [comment]
I could not reproduce the problem in the incognito window as well.
Perhaps the cause is that the script was loaded before the Google front end was fully loaded.
Reloading the page should fix it.
