### ISSUE TITLE
Script looks bad

### ISSUE THREAD

**Issue by Void48** [yakisova41/google-search-classic-navbar#19]
![image](https://github.com/yakisova41/google-search-classic-navbar/assets/85196642/bae5ef03-99ca-4904-b2c7-2141815150ca)
https://www.google.com/search?q=crx+download&hl=en

**Comment by yakisova41** [comment]
Currently, it's still classic looking without this script, so if google rolls back to the ridiculous design again, I will deal with it.
(google's site is too complicated for me to have the motivation to fix it...)

**Comment by Void48** [comment]
> Currently, it's still classic looking without this script, so if google rolls back to the ridiculous design again, I will deal with it.
> (google's site is too complicated for me to have the motivation to fix it...)

Yeah, I noticed they reverted to the previous design which is a relief. Thanks again for the work done to make the script work btw
