### ISSUE TITLE
Script no longer works again

### ISSUE THREAD

**Issue by ljcool2006** [yakisova41/google-search-classic-navbar#8]
Google has made the script not work at all again...

**Comment by Void48** [comment]
> Google has made the script not work at all again...

Can confirm but I'm guessing yakisova already knows that since he reacted to your message 👍🏻

**Comment by yakisova41** [comment]
Are there any errors displayed in the console that can be checked with F12?

What language, region, and domain (e.g., the jp part of google.co.jp) are you using?

What word do you search for to stop the script from working?

**Comment by Void48** [comment]
> Are there any errors displayed in the console that can be checked with F12?
> 
> What language, region, and domain (e.g., the jp part of google.co.jp) are you using?
> 
> What word do you search for to stop the script from working?

it's working now lol. I'll try and debug once the script stops working again

**Comment by ljcool2006** [comment]
> Are there any errors displayed in the console that can be checked with F12?
> 
> What language, region, and domain (e.g., the jp part of google.co.jp) are you using?
> 
> What word do you search for to stop the script from working?

Yes:
`Uncaught (in promise) TypeError: window.trustedTypes is undefined`

English, United States, google.com

Just about any word

I wanna let you know that I am using Firefox.

**Comment by Void48** [comment]
Searching ''youtube music'' makes the script stop working. But if I search ''lemons'' the script works.

**Comment by Void48** [comment]
> Searching ''youtube music'' makes the script stop working. But if I search ''lemons'' the script works.

Same goes for searching ''google activity'' but searching just ''activity'' will make the script work

**Comment by yakisova41** [comment]
All issues fixed in v0.2.4

**Comment by Void48** [comment]
> All issues fixed in v0.2.4

Works! Appreciate the work ❤️

**Comment by Void48** [comment]
@yakisova41 can you please make the script compatible with https://chrome.google.com/webstore/detail/google-search-geolocation/gglakldnncaidfodbmpaodhdknnlkjbb ?
It worked fine before but it doesn't work anymore after the latest update

**Comment by ljcool2006** [comment]
@yakisova41
UPDATE: It no longer works yet again. Did Google change something?

**Comment by yakisova41** [comment]
Version 0.2.5, which fixes the problem, has been released to greasyfork.
If you are using the extended feature version, please wait for the release as soon as the review process is completed.

**Comment by Void48** [comment]
> Version 0.2.5, which fixes the problem, has been released to greasyfork. If you are using the extended feature version, please wait for the release as soon as the review process is completed.

❤️

**Comment by Void48** [comment]
![image](https://github.com/yakisova41/google-search-classic-navbar/assets/85196642/e7ec67de-b549-41bf-bc20-6b2bcaf26357)
https://www.google.com/search?q=iOS+17&hl=en
@yakisova41 another bug

**Comment by yakisova41** [comment]
> ![image](https://private-user-images.githubusercontent.com/85196642/289264434-e7ec67de-b549-41bf-bc20-6b2bcaf26357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjM2MjIsIm5iZiI6MTcwMjEyMzMyMiwicGF0aCI6Ii84NTE5NjY0Mi8yODkyNjQ0MzQtZTdlYzY3ZGUtYjU0OS00MWJmLWJjMjAtNmIyYmNhZjI2MzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEyMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0Y2E2ZTE5OTczNjcyZTExZjUyMTNkNTdmODE3ZDUwYzNhYzA3YjVmNjJiMWYwMzBhZTk1MWNiZDZhM2VmYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avtkCnV2CRzbzBqpewudwCStWIQYKPdnUHmJFnLaX1E) https://www.google.com/search?q=iOS+17&hl=en @yakisova41 another bug

Version 0.2.6 has been released to address this shitty design

**Comment by ljcool2006** [comment]
@yakisova41
Now it's being replaced with a huge block of nothingness...
![Screenshot_2024-01-01 date_default_timezone_set - Google Search](https://github.com/yakisova41/google-search-classic-navbar/assets/51834343/b2d7a937-1bd4-4b5f-96b5-67b187df84e4)
